In [3]:
import numpy as np
A = np.array([1, 2])
B = np.array([[3,4,5], [6,7, 8]])
C = np.dot(A, B)
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Matrix C = A * B:")
print(C)

Matrix A:
[1 2]
Matrix B:
[[3 4 5]
 [6 7 8]]
Matrix C = A * B:
[15 18 21]


In [4]:
import numpy as np
A = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:")
print(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]
Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [6]:
import numpy as np

# Define a 3x3 matrix A
A = np.array([[5, 4, 2],
              [0, 1, -1],
              [0, 0, 3]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display the results
print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors (columns):")
print(eigenvectors)


Matrix A:
[[ 5  4  2]
 [ 0  1 -1]
 [ 0  0  3]]

Eigenvalues:
[5. 1. 3.]

Eigenvectors (columns):
[[ 1.         -0.70710678  0.        ]
 [ 0.          0.70710678 -0.4472136 ]
 [ 0.          0.          0.89442719]]


In [7]:
import numpy as np

# Define a 4x4 matrix A
A = np.array([[4, 2, 1, 3],
              [0, 1, -1, 0],
              [0, 0, 3, 2],
              [0, 0, 0, 2]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display the results
print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors (columns):")
print(eigenvectors)


Matrix A:
[[ 4  2  1  3]
 [ 0  1 -1  0]
 [ 0  0  3  2]
 [ 0  0  0  2]]

Eigenvalues:
[4. 1. 3. 2.]

Eigenvectors (columns):
[[ 1.         -0.5547002   0.         -0.6401844 ]
 [ 0.          0.83205029 -0.4472136   0.51214752]
 [ 0.          0.          0.89442719 -0.51214752]
 [ 0.          0.          0.          0.25607376]]


In [1]:
import numpy as np

# New 3x3 matrix
C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

U, S, V = np.linalg.svd(C)
print("Matrix C:")
print(C)
print("U matrix:")
print(U)
print("Singular values:")
print(S)
print("V matrix:")
print(V)


Matrix C:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
U matrix:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values:
[1.68481034e+01 1.06836951e+00 3.33475287e-16]
V matrix:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [2]:
import numpy as np

A1 = np.array([[2, 4, 1],
               [0, 3, -1],
               [5, 2, 0]])

A2 = np.array([[1, 0, 2],
               [-1, 3, 1],
               [4, 1, 0]])

# Combine vertically (6 rows, 3 columns)
combined = np.vstack((A1, A2))

# Compute SVD on combined matrix
U, S, V = np.linalg.svd(combined)

print("Combined matrix:")
print(combined)
print("\nU matrix:")
print(U)
print("\nSingular values:")
print(S)
print("\nV matrix:")
print(V)


Combined matrix:
[[ 2  4  1]
 [ 0  3 -1]
 [ 5  2  0]
 [ 1  0  2]
 [-1  3  1]
 [ 4  1  0]]

U matrix:
[[-0.52347323  0.3855573   0.20101026 -0.52700129 -0.43678585 -0.26154157]
 [-0.22742137  0.45979625 -0.51857132  0.55941691 -0.34678977  0.18638746]
 [-0.64578966 -0.33678652 -0.1296224   0.28383081  0.36656152 -0.48764876]
 [-0.11922502 -0.10172696  0.77122014  0.52999681 -0.29654983  0.10871106]
 [-0.15188907  0.61924431  0.27021234  0.02642458  0.68309574  0.23050691]
 [-0.46896282 -0.36427452 -0.07798384 -0.21718092  0.00510241  0.7707807 ]]

Singular values:
[7.92704349 4.86508881 2.54811546]

V matrix:
[[-0.77192486 -0.6297892  -0.08658852]
 [-0.63531982  0.76905139  0.07020456]
 [-0.02237695 -0.10920405  0.99376745]]


In [3]:
import numpy as np

A1 = np.array([[2, 4, 1],
               [0, 3, -1],
               [5, 2, 0]])

A2 = np.array([[1, 0, 2],
               [-1, 3, 1],
               [4, 1, 0]])

# Combine horizontally (3 rows, 6 columns)
combined = np.hstack((A1, A2))

# Compute SVD
U, S, V = np.linalg.svd(combined)

print("Combined matrix (columns-wise):")
print(combined)
print("\nU matrix:")
print(U)
print("\nSingular values:")
print(S)
print("\nV matrix:")
print(V)


Combined matrix (columns-wise):
[[ 2  4  1  1  0  2]
 [ 0  3 -1 -1  3  1]
 [ 5  2  0  4  1  0]]

U matrix:
[[ 0.55411217  0.3291792   0.76459189]
 [ 0.25293941  0.80848636 -0.53138636]
 [ 0.79308345 -0.48784307 -0.36472974]]

Singular values:
[7.9350889  4.78213803 2.6768489 ]

V matrix:
[[ 0.63939316  0.57484344  0.03795455  0.43774009  0.19557458  0.1715373 ]
 [-0.37239765  0.57850478 -0.10022863 -0.508283    0.40517776  0.30673409]
 [-0.11000431  0.2744828   0.48414322 -0.06087034 -0.73178909  0.37275074]
 [-0.64099216  0.19511556 -0.21160648  0.71094122 -0.0290352   0.00109367]
 [-0.16651996 -0.13370623  0.83304738  0.154317    0.48274428 -0.05974977]
 [ 0.04237421 -0.45121944 -0.12399104  0.13067381  0.1678726   0.8567233 ]]


In [4]:
import numpy as np

A = np.array([[2, 4, 1],
              [0, 3, -1],
              [5, 2, 0]])

# Compute SVD
U, S, Vt = np.linalg.svd(A)

# Build Sigma matrix from singular values
Sigma = np.diag(S)

# Reconstruct A using the formula A = U * Sigma * V^T
A_reconstructed = U @ Sigma @ Vt

print("Original matrix A:\n", A)
print("\nReconstructed matrix A:\n", A_reconstructed)


Original matrix A:
 [[ 2  4  1]
 [ 0  3 -1]
 [ 5  2  0]]

Reconstructed matrix A:
 [[ 2.00000000e+00  4.00000000e+00  1.00000000e+00]
 [ 1.16298342e-17  3.00000000e+00 -1.00000000e+00]
 [ 5.00000000e+00  2.00000000e+00  4.79278172e-17]]


In [6]:
import numpy as np

# Define a 3x3 matrix
A = np.array([[4, 2, 1],
              [3, 5, 7],
              [1, 0, 6]])

# Calculate the determinant
det = np.linalg.det(A)

# Display the matrix and its determinant
print("Matrix A:")
print(A)
print("Determinant of A:")
print(det)


Matrix A:
[[4 2 1]
 [3 5 7]
 [1 0 6]]
Determinant of A:
93.00000000000003


In [14]:
import numpy as np

# Generate a random 3x3 float matrix with values between 0 and 1
A = np.random.randint(1,10,(3, 3))

# Calculate the determinant
det = np.linalg.det(A)

# Display the matrix and its determinant
print("Random 3x3 Float Matrix A:")
print(A)
print("Determinant of A:")
print(det)


Random 3x3 Float Matrix A:
[[6 9 5]
 [4 6 9]
 [9 3 6]]
Determinant of A:
356.9999999999999


In [15]:
import numpy as np

# Define a new 3x1 vector
v = np.array([5, -2, 8])

# Calculate L1 and L2 norms
L1_norm = np.linalg.norm(v, ord=1)
L2_norm = np.linalg.norm(v)

# Display the vector and its norms
print("Vector v:")
print(v)
print("L1 norm of v:")
print(L1_norm)
print("L2 norm of v:")
print(L2_norm)


Vector v:
[ 5 -2  8]
L1 norm of v:
15.0
L2 norm of v:
9.643650760992955


In [16]:
import numpy as np

# Define a 2x3 matrix
A = np.array([[1, -2, 3],
              [4, 0, -5]])

# Calculate norms
L1_norm = np.linalg.norm(A, ord=1)         # Max column sum
L2_norm = np.linalg.norm(A, ord=2)         # Largest singular value

# Display results
print("Matrix A (2x3):")
print(A)
print("L1 norm (max column sum):", L1_norm)
print("L2 norm (largest singular value):", L2_norm)


Matrix A (2x3):
[[ 1 -2  3]
 [ 4  0 -5]]
L1 norm (max column sum): 8.0
L2 norm (largest singular value): 6.7017963836025345
