****Week 1: Exercise 1 - Matrix Multiplication****

In [3]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Matrix C = A * B:")
print(C)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix C = A * B:
[[19 22]
 [43 50]]


****Week 1: Exercise 2- Eigen Decomposition****

In [4]:
import numpy as np
A = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:")
print(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)



Matrix A:
[[4 2]
 [1 3]]
Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


****Week 1: Exercise 3- Singular Value Decomposition (SVD)****

In [5]:
import numpy as np
A = np.array([[3, 2, 2], [2, 3, -2]])
U, S, V = np.linalg.svd(A)
print("Matrix A:")
print(A)
print("U matrix:")
print(U)
print("Singular values:")
print(S)
print("V matrix:")
print(V)

Matrix A:
[[ 3  2  2]
 [ 2  3 -2]]
U matrix:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Singular values:
[5. 3.]
V matrix:
[[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


****Week 1: Exercise 4- Determinant Calculation****

In [6]:
import numpy as np
A = np.array([[6, 1], [2, 3]])
det = np.linalg.det(A)
print("Matrix A:")
print(A)
print("Determinant of A:")
print(det)

Matrix A:
[[6 1]
 [2 3]]
Determinant of A:
15.999999999999998


****Week 1: Exercise 5 - Norm Calculation****

In [8]:
import numpy as np
v = np.array([3, 4])
L1_norm = np.linalg.norm(v, ord=1)
L2_norm = np.linalg.norm(v)
print("Vector v:")
print(v)
print("L1 norm of v:")
print(L1_norm)
print("L2 norm of v:")
print(L2_norm)

Vector v:
[3 4]
L1 norm of v:
7.0
L2 norm of v:
5.0
